services:
  web:
    image: ghcr.io/bohdanmoroz11/personal-website:latest
    container_name: bohdanmoroz-web
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
